### ISSUE TITLE
Should I reuse RapidClient for multiple requests? Thread safety?

### ISSUE THREAD

**Issue by davidwebster48** [eWAYPayment/eway-rapid-java#1]
Should I create a new RapidClient for each transaction, or should I create one instance and keep re-using it?

Is a RapidClient thread-safe? i.e. Will I have problems if many threads share a RapidClient and more than one is processing a transaction at the same time?

**Comment by incarnate** [comment]
Hi David,

The RapidClient is designed to be reusable for multiple transactions. Each transaction is atomic, only the common details like API key & password are kept (so if you are using multiple credentials for some reason you'd want separate clients for each).

This also means it should be thread-safe as well - however we haven't done any of testing specifically for that.

**Comment by davidwebster48** [comment]
Ok, thanks John!
