### ISSUE TITLE
RapidClient reuse and thread safety

### ISSUE THREAD

**Issue by loodakrawa** [eWAYPayment/eway-rapid-java#9]
Hi,

Is the RapidClient reausable for multiple requests? If yes, is it thread safe?

Thanks

**Comment by incarnate** [comment]
Hi loodakrawa,

Yes, the RapidClient is designed so that it can be reused for multiple requests.
We haven't done any testing around thread safety and don't have any locks in the SDK, so while I don't think there should be any issues I can't guarantee it.

Hope that helps!

**Comment by loodakrawa** [comment]
It does. Thanks for the info!
